#!/bin/sh
# xcompmgr -c &
# gnome-settings-daemon &      # handles themes, starts gnome-screensaver.
# gnome-sound-applet &         # sound volume
# nm-applet &                  # Network Manager
# eval `gnome-keyring-daemon`  # SSH/GPG agent
# eval "$(ssh-agent -s)"
dropbox start                # Dropbox daemon
xautolock -time 60 -locker "lock.sh" &
# xflux -l 37.333 -g -121.900  # f.lux
xset r rate 250 30
xset m 4 4
synclient MaxTapTime=0       # Disable touchpad tap-to-click
exec awesome                 # when it terminates, X will be terminated
